/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/abduction.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0.01, 0.04, -0.01]} scale={0.70}>
        <mesh geometry={nodes.Cylinder005.geometry} material={materials.Blue} />
        <mesh geometry={nodes.Cylinder005_1.geometry} material={materials.LightsMain} />
        <mesh geometry={nodes.Cylinder005_2.geometry} material={materials.Ufo2} />
        <mesh geometry={nodes.Cylinder005_3.geometry} material={materials.BottomLight} />
        <mesh geometry={nodes.Cylinder005_4.geometry} material={materials.Vents} />
        <mesh geometry={nodes.Cylinder005_5.geometry} material={materials.Bottom} />
        <mesh geometry={nodes.Cylinder005_6.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Cylinder005_7.geometry} material={materials.White} />
        <mesh geometry={nodes.Cylinder005_8.geometry} material={materials['Box Red']} />
        <mesh geometry={nodes.Cylinder005_9.geometry} material={materials.Sign2} />
        <mesh geometry={nodes.Cylinder005_10.geometry} material={materials.Green} />
        <mesh geometry={nodes.Cylinder005_11.geometry} material={materials.Pink} />
        <mesh geometry={nodes.Cylinder005_12.geometry} material={materials.Cow} />
        <mesh geometry={nodes.Cylinder005_13.geometry} material={materials.hooves} />
        <mesh geometry={nodes.Cylinder005_14.geometry} material={materials.M_darkGrey} />
        <mesh geometry={nodes.Cylinder005_15.geometry} material={materials.M_black} />
        <mesh geometry={nodes.Cylinder005_16.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Cylinder005_17.geometry} material={materials.Sign} />
        <mesh geometry={nodes.Cylinder005_18.geometry} material={materials.Grass1} />
        <mesh geometry={nodes.Cylinder005_19.geometry} material={materials.Ground} />
        <mesh geometry={nodes.Cylinder005_20.geometry} material={materials.Rocks} />
        <mesh geometry={nodes.Cylinder005_21.geometry} material={materials.Beam} />
      </group>
    </group>
  )
}

useGLTF.preload('/abduction.gltf')
